// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYzsTkqeRD8ayh3xU54LXVC9xjZVd963Y',
    appId: '1:223103795490:web:d54b3ccd76fc336373e57b',
    messagingSenderId: '223103795490',
    projectId: 'afwms-d3141',
    authDomain: 'afwms-d3141.firebaseapp.com',
    storageBucket: 'afwms-d3141.firebasestorage.app',
    measurementId: 'G-6GW2WQFR4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdxyQcVxV1gNymE3b_THcvKQJRMa6SDc',
    appId: '1:223103795490:android:50ac9a84eddb9ee373e57b',
    messagingSenderId: '223103795490',
    projectId: 'afwms-d3141',
    storageBucket: 'afwms-d3141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeCmrChz07uCUoPdtln5egJmG1QPrMtfw',
    appId: '1:223103795490:ios:c878119c41daeff073e57b',
    messagingSenderId: '223103795490',
    projectId: 'afwms-d3141',
    storageBucket: 'afwms-d3141.firebasestorage.app',
    iosBundleId: 'com.example.afwms.afwmsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeCmrChz07uCUoPdtln5egJmG1QPrMtfw',
    appId: '1:223103795490:ios:c878119c41daeff073e57b',
    messagingSenderId: '223103795490',
    projectId: 'afwms-d3141',
    storageBucket: 'afwms-d3141.firebasestorage.app',
    iosBundleId: 'com.example.afwms.afwmsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYzsTkqeRD8ayh3xU54LXVC9xjZVd963Y',
    appId: '1:223103795490:web:a329f2aa48f6f9b473e57b',
    messagingSenderId: '223103795490',
    projectId: 'afwms-d3141',
    authDomain: 'afwms-d3141.firebaseapp.com',
    storageBucket: 'afwms-d3141.firebasestorage.app',
    measurementId: 'G-8GNHSMDBT5',
  );
}
